language: node_js
node_js:
  - "12"
# if using Ubuntu 16 need this library for cypress
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
      - libgconf-2-4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
script:
  - yarn install
  - mv packages/upswyng-native/config.example.ts packages/upswyng-native/config.ts
  - yarn build:local-packages
  - yarn workspace @upswyng/upswyng-server build:bin
  - yarn lint:ci
  - yarn test:ci
  - yarn workspace @upswyng/upswyng-server build:server
  - yarn workspace @upswyng/upswyng-server build:worker
  - CI=false yarn workspace @upswyng/upswyng-web build
